name: Release Server
on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    permissions: write-all
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Write value to Properties-file
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './gradle.properties'
          property: |
            'version'
          value: |
            'Build ${{github.run_number}}'

      - run: git tag ${{github.run_number}}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Buid JS bundle
        run: |
          ./gradlew :client:jsBrowserProductionWebpack
      - name: server.zip
        run: ./gradlew :server:distZip

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Build #${{github.run_number}}"
          automatic_release_tag: "${{github.run_number}}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: server/build/distributions/server.zip
          prerelease: false